#application name
spring.application.name=smartloading

#postgreSQL in kubernetes
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/mydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

#hibernate and jpa for Kubernetes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# redis configuration (kubernetes)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:password123}
spring.data.redis.timeout=2s

# enable caching with redis in kubernetes
spring.cache.type=redis

spring.session.store-type=redis
server.servlet.session.timeout=30m
