apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: smartloading
spec:
  serviceName: "redis"
  replicas: 1  # Redis statefulset with 1 replica
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartloading-secrets
                  key: REDIS_PASSWORD
          command: ["sh", "-c"]
          args:
            - |
              redis-server --requirepass "$REDIS_PASSWORD"
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: smartloading
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
